### ISSUE TITLE
Bill of Materials (BOM)

### ISSUE THREAD

**Issue by magnetomage** [frenchguycooking/doughsheeter#3]
Would you be willing to assemble a complete bill of materials? After watching your video it's not all that clear what parts are required. So, if you're game, a complete BOM and some basic instructions would be awesome.

**Comment by VedantKalbag** [comment]
Did you get any of these details? I'm struggling a bit trying to figure out what needs to be printed in what quantities, and how it needs to be assembled

**Comment by magnetomage** [comment]
I did not. however another user @mercy0 has done a #D model and short write up on another thread that had this info. https://github.com/frenchguycooking/doughsheeter/issues/2#issuecomment-536134070
